from django.db import models

# Create your models here.
class data(models.Model):#membuat model data transaksi penjualan
	invoice = models.PositiveIntegerField(primary_key=True)
	almond = models.BooleanField(default=False)
	alpukat = models.BooleanField(default=False)
	anggur = models.BooleanField(default=False)
	apel = models.BooleanField(default=False)
	asam_bangkok = models.BooleanField(default=False)
	avomango = models.BooleanField(default=False)
	blueberry_arg = models.BooleanField(default=False)
	buah_naga = models.BooleanField(default=False)
	buah_tin = models.BooleanField(default=False)
	cherry_aus = models.BooleanField(default=False)
	chia_seed = models.BooleanField(default=False)
	delima = models.BooleanField(default=False)
	durian = models.BooleanField(default=False)
	grapeola = models.BooleanField(default=False)
	jambu_kristal = models.BooleanField(default=False)
	jeruk = models.BooleanField(default=False)
	kiwi = models.BooleanField(default=False)
	kurma = models.BooleanField(default=False)
	lemon = models.BooleanField(default=False)
	lengkeng = models.BooleanField(default=False)
	mangga = models.BooleanField(default=False)
	melon_golden = models.BooleanField(default=False)
	nanas_honi = models.BooleanField(default=False)
	nectarin_aus = models.BooleanField(default=False)
	peach_aus = models.BooleanField(default=False)
	pear = models.BooleanField(default=False)
	pisang = models.BooleanField(default=False)
	plum = models.BooleanField(default=False)
	salak_pondoh = models.BooleanField(default=False)